# Generated by Django 4.2 on 2023-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_blog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="high_regulation_banner_link",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="low_regulation_banner_link",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="blog_banners"),
        ),
    ]
