# Generated by Django 4.2 on 2023-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_blog_high_regulation_banner_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
