# Generated by Django 4.2 on 2023-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_category_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
