# Generated by Django 4.2 on 2023-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_tag_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
