# Generated by Django 4.2 on 2023-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_blog_meta_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
