# Generated by Django 4.2 on 2023-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_category_meta_description_tag_meta_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="schema_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
