# Generated by Django 4.2 on 2023-04-09 16:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_blog_schema_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="schema_data",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
