# Generated by Django 4.2 on 2023-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_alter_blog_schema_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="schema_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
