# Generated by Django 4.2 on 2023-04-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_alter_blog_schema_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
