# Generated by Django 4.2 on 2023-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0013_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_banners"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="high_regulation_banner_link",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_tag",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="tag_banners"),
        ),
        migrations.AddField(
            model_name="tag",
            name="high_regulation_banner_link",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_tag",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
