# Generated by Django 4.2 on 2023-04-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_category_schema_data_tag_schema_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
