# Generated by Django 4.2 on 2023-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_remove_blog_new_slug_blog_custom_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="custom_slug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="custom_slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
