# Generated by Django 4.2 on 2023-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_follow_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
