# Generated by Django 4.2 on 2023-04-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_slider_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="image_link",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="slider"),
        ),
    ]
