# Generated by Django 4.2 on 2023-04-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_headerlogo_remove_slider_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrollingText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
